name: Publish rstudio server

on:
  push:
    branches: [ "main" ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yzhangtufts/rstudio_server
          flavor: latest=true
          tags: |
            type=ref, event=branch
            type=ref, event=pr
            type=semver, pattern={{version}}

      - name: Login to DockerHub
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Move cache
        run: |
          docker builder prune -af
